### ISSUE TITLE
lagarta+

### ISSUE THREAD

**Issue by Basilio40** [CodandoErrado/desafio-1-btc-imagens#1]
![Anticarsia_gemmatalis11](https://user-images.githubusercontent.com/42722896/90322356-9f732c80-df29-11ea-8eab-5ac5a14c0d25.jpg)
![Anticarsia_gemmatalis12 (1)](https://user-images.githubusercontent.com/42722896/90322359-a00bc300-df29-11ea-843b-f95a2be0633a.jpg)
![Anticarsia_gemmatalis12](https://user-images.githubusercontent.com/42722896/90322361-a0a45980-df29-11ea-997a-630f6f55f3af.jpg)
![Anticarsia_gemmatalis13](https://user-images.githubusercontent.com/42722896/90322362-a13cf000-df29-11ea-90ba-8ce64f617994.jpg)
![anticarsia_gemmatalis103](https://user-images.githubusercontent.com/42722896/90322363-a13cf000-df29-11ea-83a5-ee53f2bd0c21.jpg)
![lagarta](https://user-images.githubusercontent.com/42722896/90322364-a1d58680-df29-11ea-9ddb-e28f9fdda74d.jpeg)
![lagarta1](https://user-images.githubusercontent.com/42722896/90322365-a1d58680-df29-11ea-8a93-253b6f835f01.jpg)
![lagarta2](https://user-images.githubusercontent.com/42722896/90322366-a26e1d00-df29-11ea-8c8a-001a72b6860f.jpg)
![lagarta3](https://user-images.githubusercontent.com/42722896/90322367-a39f4a00-df29-11ea-89e4-c95ae117fbfa.jpg)
![lagarta4](https://user-images.githubusercontent.com/42722896/90322368-a39f4a00-df29-11ea-9b7d-bf9c7aaa4b93.jpg)
![lagarta5](https://user-images.githubusercontent.com/42722896/90322369-a437e080-df29-11ea-8d6e-97cf42da6d45.jpg)
![lagarta6](https://user-images.githubusercontent.com/42722896/90322370-a437e080-df29-11ea-8ef9-5c58850c2a72.jpg)
![lagarta7](https://user-images.githubusercontent.com/42722896/90322371-a4d07700-df29-11ea-8d6e-b2124773c0af.jpg)
![lagarta8](https://user-images.githubusercontent.com/42722896/90322372-a5690d80-df29-11ea-8abb-5cb455c9162a.jpg)
![lagarta9](https://user-images.githubusercontent.com/42722896/90322373-a5690d80-df29-11ea-8430-38bb927f6910.jpg)
![lagarta10](https://user-images.githubusercontent.com/42722896/90322374-a601a400-df29-11ea-9f32-d33bc668c410.jpg)
![Anticarsia_gemmatalis3](https://user-images.githubusercontent.com/42722896/90322375-a601a400-df29-11ea-84ab-d8332bd260cc.jpg)
![Anticarsia_gemmatalis9](https://user-images.githubusercontent.com/42722896/90322376-a69a3a80-df29-11ea-9934-3f36914c178c.jpg)
![Anticarsia_gemmatalis11 (1)](https://user-images.githubusercontent.com/42722896/90322378-a69a3a80-df29-11ea-8c94-94e836c293cf.jpg)

**Comment by Basilio40** [comment]
Mais algumas imagens

**Comment by NicolasFrancaX** [comment]
@Basilio40 , muito obrigado! se tu puder adicionar na pasta pra gente, eu ficaria grato. 

caso você não esteja no nosso grupo de membros, me manda e-mail para: nicolasfranca9@gmail.com que eu te adiciono!

**Comment by justbrendo** [comment]
> Mais algumas imagens

Opá, Basilo40, tudo bem ? Agradecemos muito por você estar querendo nos ajudar com o repositório :D
Entretanto, peço que envie tais imagens através dos Pull Request. Certifique-se de que elas seguem os padrões de qualidades estabelecidos no nosso servidor do Discord, pois noto que algumas deles apresentam divergências.
